# Outpost Teleport
npc-id: 9
teleport-cooldown: 1200 # 30 mins
locations:
  desert:
    world: world
    x: 2192
    y: 187
    z: 1596
  feyforest:
    world: world
    x: -3441
    y: 191
    z: 1415
  oaklands:
    world: world
    x: 1689
    y: 137
    z: -1978
  frostland:
    world: world
    x: -2021
    y: 151
    z: -2015

# Database
host: ms2616.gamedata.io
user: ni12126628_1_DB
password: sXF4FLNx
port: 3306
name: ni12126628_1_DB

# Clan System
max-clan-tag-length: 3
max-clan-name-length: 25
max-members-per-clan: 30
newbie-protection-hours: 24
clan-home-cooldown: 1200 # 30 mins
clan-sethome-cooldown: 172800 # 48 hrs

# Music System
spawnSound:
  MusicKey: minecraft:custom.spawn
  category: music
  volume: 0.7
  pitch1am: 0.7
  pitch1pm: 1.0
  loopMs: 70000
  regions:
    - "spawn"

singularitySound:
  MusicKey: minecraft:custom.singularity
  category: music
  volume: 0.7
  pitch1am: 0.7
  pitch1pm: 1.0
  loopMs: 120000
  regions:
    - "singularity"

# Custom Repair
custom-repair:
  enabled: true
  base-cost-per-durability: 0.25
  cost-growth-factor: 1.5
  npcs: [11]

# Custom Rename
custom-rename:
  enabled: true
  price: 1000.0

# Random Information
random-information:
  interval-seconds: 1200

# Chest Limiter
chest-limiter:
  enabled: true
  max-chests-per-chunk: 50
  limit-message: "&cThis chunk already has the maximum number of chests (%max%)."

# NPC Shops
npc-shops:
  example-shop:
    npc-id: 25
    title: "&6Example Shop"
    size: 27



