# Outpost Teleport
npc-id: 9
teleport-cooldown: 1200
locations:
  desert:
    world: world
    x: 2192
    y: 187
    z: 1596
  feyforest:
    world: world
    x: -3441
    y: 191
    z: 1415
  oaklands:
    world: world
    x: 1689
    y: 137
    z: -1978
  frostland:
    world: world
    x: -2021
    y: 151
    z: -2015

# Database
host: ms2616.gamedata.io
user: ni12126628_1
password: Jx3iWmrt
port: 21

# Clan System
max-clan-tag-length: 3
max-clan-name-length: 25
max-members-per-clan: 30
newbie-protection-hours: 24

