name: ElytriaEssentials
version: '2.3'
main: me.luisgamedev.elytriaEssentials.ElytriaEssentials
api-version: '1.21'
depend: [Vault, Citizens, WorldGuard]
softdepend: [WGRegionEvents, MMOItems, MMOCore, MythicHUD, MythicLib]
commands:
  clan:
    description: Clan management command
    usage: /clan
  npcshop:
    description: Manage NPC buy shops
    usage: /npcshop additem <shopId> <price>
    permission: elytria.npcshop.manage
    default: op
    permission-message: You do not have permission to manage NPC shops.
  mmocd:
    description: Reduce a player's MMOCore/MythicLib skill cooldown (console-only).
    usage: /mmocd <abilityId> <percent(1-100)> <playerName>
    permission: elytria.cooldownAPI.use
    default: op
permissions:
  elytria.classchange.bypass:
    description: Allows the player to bypass the class change cooldown.
    default: op
