name: ElytriaEssentials
version: '1.9'
main: me.luisgamedev.elytriaEssentials.ElytriaEssentials
api-version: '1.21'
depend: [WorldGuard]
softdepend: [Citizens, WGRegionEvents]
commands:
  clan:
    description: Clan management command
    usage: /clan
