name: ElytriaEssentials
version: '2.0'
main: me.luisgamedev.elytriaEssentials.ElytriaEssentials
api-version: '1.21'
depend: [WorldGuard]
softdepend: [Citizens, WGRegionEvents, MMOItems, Vault]
commands:
  clan:
    description: Clan management command
    usage: /clan
